function PlotNice()
if (strcmp(mode,'T&C'))
        figure('Units','inches',...
            'OuterPosition',[0 0 8 8],...
            'PaperPositionMode','auto');
        [ha, pos] = tight_subplot(3, 2, 0.07, 0.06, 0.06);
        set(ha, 'XTickLabelMode', 'auto')
        set(ha, 'YTickLabelMode', 'auto')
        cmap = colormap('gray');
        color1 = cmap(1,:);
        color2 = cmap(floor(size(cmap,1)/2),:);
        red = [0.9373    0.2980    0.2980];
        gray = [0.2471    0.2471    0.2471];
        for ii=1:numAbs
            disp(ii)
            axes(ha(ii));
            hold on;
            T = SymbolicSet(['T/T' num2str(ii) '.bdd'],'projection',[1 2]);
            C = SymbolicSet(['C/C' num2str(ii) '.bdd'],'projection',[1 2]);
            try
%                 s = subplot(3,numAbs/3,ii); hold on;
%                 plotCells(T,'facecolor',red,'EdgeColor',red);
%                 plotCells(C,'facecolor',gray,'EdgeColor',gray);

                pT = T.points;
                pC = C.points;
                plot(pT(:,1),pT(:,2),'rs', 'MarkerSize', 10/ii);
                plot(pC(:,1),pC(:,2),'ks', 'MarkerSize', 10/ii);
%                 set(s,...
%                     'Units','normalized',...
%                     'OuterPosition',[0 0 1 1],...
%                     'YTick',0:2:12,...
%                     'XTick',0:2:12,...
%                     'FontUnits','points',...
%                     'FontWeight','normal',...
%                     'FontSize',9,...
%                     'FontName','Times')
                axis([1.1 1.6 5.4 5.9]);
                title({['$L =' num2str(numAbs + 1 - ii) '$']},...
                    'FontUnits','points',...
                        'interpreter','latex',...
                        'FontSize',14,...
                        'FontName','Times');
                ylabel({'$x_2$'},...
                        'FontUnits','points',...
                        'interpreter','latex',...
                        'FontSize',10,...
                        'FontName','Times');%,...
        %                 'Units','Normalized',...
        %                 'Position',[-0.1,0.5,0])
                xlabel({'$x_1$'},...
                        'FontUnits','points',...
                        'interpreter','latex',...
                        'FontSize',10,...
                        'FontName','Times',...
                        'Units','Normalized',...
'Position',[0.5,-0.05,0]);
                box on;
            catch
                warning(['There are no points in T or C' num2str(ii)]);
            end
        end

        savefig('dcdc6A_cdc');
        print -depsc dcdc6A_cdc.eps
    end 